#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  start.sh — smart launcher for the Docker stack
#
#  Auto-detects an existing host Ollama cache (~/.ollama) and bind-mounts it
#  into the container so you don't re-download GBs of models.
#
#  Usage:
#    ./start.sh          # starts stack in background + tails ollama-init
#    ./start.sh logs     # tail all app logs
#    ./start.sh stop     # stops everything
#    ./start.sh reset    # stops + deletes volumes (re-downloads models!)
# ─────────────────────────────────────────────────────────────────────────────
set -e

cd "$(dirname "$0")"
OVERRIDE="docker-compose.override.yml"

write_override() {
  local host_cache="$1"
  cat > "$OVERRIDE" <<EOF
# AUTO-GENERATED by start.sh — do not edit (run ./start.sh to regenerate)
# Bind-mounts the host's existing Ollama cache so we don't re-download models.
services:
  ollama:
    volumes:
      - ${host_cache}:/root/.ollama
  ollama-init:
    volumes:
      - ${host_cache}:/root/.ollama
volumes:
  ollama_data:
    external: false
EOF
}

cmd="${1:-up}"

case "$cmd" in
  logs)
    docker compose logs -f
    exit 0
    ;;
  stop|down)
    docker compose down
    exit 0
    ;;
  reset)
    docker compose down -v
    rm -f "$OVERRIDE"
    echo "Stack + volumes removed. Run ./start.sh to rebuild."
    exit 0
    ;;
esac

# ─── Detect host Ollama cache ────────────────────────────────────────────────
HOST_CACHE=""
for candidate in "$HOME/.ollama" "/usr/share/ollama/.ollama" "/var/lib/ollama"; do
  if [ -d "$candidate/models" ] && [ -n "$(ls -A "$candidate/models" 2>/dev/null)" ]; then
    HOST_CACHE="$candidate"
    break
  fi
done

if [ -n "$HOST_CACHE" ]; then
  echo "✓ Found host Ollama cache at: $HOST_CACHE"
  # List what's there so user knows what will be reused
  models=$(ls "$HOST_CACHE/models/manifests/registry.ollama.ai/library" 2>/dev/null | tr '\n' ' ')
  [ -n "$models" ] && echo "  Models present: $models"
  write_override "$HOST_CACHE"
  echo "✓ Wrote $OVERRIDE — container will reuse these models."
else
  echo "ℹ No host Ollama cache found — models will be downloaded fresh (~25 GB, 10-20 min)."
  # Remove any stale override so we use the default named volume
  rm -f "$OVERRIDE"
fi

# ─── Boot ────────────────────────────────────────────────────────────────────
echo ""
echo "▶ Starting stack..."
docker compose up -d --build

echo ""
echo "▶ Waiting for ollama-init to finish (models check/pull)..."
docker compose logs -f ollama-init &
LOG_PID=$!

# Wait for init container to exit
while docker inspect -f '{{.State.Status}}' nyc_ollama_init 2>/dev/null | grep -q running; do
  sleep 2
done
kill $LOG_PID 2>/dev/null || true

echo ""
echo "✓ Stack ready!"
echo "  User portal:  http://localhost:9000"
echo "  Admin portal: http://localhost:9001"
echo ""
echo "  Tail app logs:  ./start.sh logs"
echo "  Stop stack:     ./start.sh stop"
